use anyhow::{Context, Result};
use std::path::PathBuf;
use terminal_size::{terminal_size, Width};
use tokio::sync::mpsc::UnboundedReceiver;
use tycode_core::{
    chat::{ChatActor, ChatEvent, MessageSender},
    formatter::{CompactFormatter, EventFormatter, VerboseFormatter},
};

use crate::auto_driver::{drive_auto_conversation, AutoDriverConfig};
use crate::github;

pub async fn run_auto_pr(
    issue_number: u32,
    workspace_roots: Vec<PathBuf>,
    profile: Option<String>,
    draft: bool,
    compact: bool,
) -> Result<()> {
    let terminal_width = terminal_size()
        .map(|(Width(w), _)| w as usize)
        .unwrap_or(80);
    let mut formatter: Box<dyn EventFormatter> = if compact {
        Box::new(CompactFormatter::new(terminal_width))
    } else {
        Box::new(VerboseFormatter::new())
    };

    formatter.print_system("Starting auto-PR mode...");

    let issue = github::fetch_issue(issue_number)
        .context("Failed to fetch GitHub issue - ensure gh CLI is installed and authenticated")?;

    formatter.print_system(&format!("Fetched issue #{}: {}", issue.number, issue.title));

    github::ensure_clean_working_tree().context("Cannot proceed with uncommitted changes")?;

    let branch_name = github::create_branch(issue_number).context("Failed to create branch")?;

    formatter.print_system(&format!("Created branch: {}", branch_name));

    let (mut actor, mut event_rx) = ChatActor::builder()
        .workspace_roots(workspace_roots)
        .profile(profile)
        .agent_name("auto_pr".to_string())
        .build()?;

    let initial_message = format!(
        "Please help me resolve this GitHub issue:\n\n# {}\n\n{}",
        issue.title, issue.body
    );

    actor.send_message(initial_message)?;

    let config = AutoDriverConfig {
        initial_agent: "auto_pr".to_string(),
        max_messages: 500,
    };
    let drive_result =
        drive_auto_conversation(&mut actor, &mut event_rx, &mut *formatter, config).await;

    match drive_result {
        Ok(summary) => {
            formatter.print_system("Agent completed the task successfully");
            formatter.print_system("Requesting commit message from agent...");

            let commit_message = request_commit_message(&mut actor, &mut event_rx, &mut *formatter)
                .await
                .context("Failed to generate commit message")?;

            if commit_message.to_lowercase().contains("claude") {
                return Err(anyhow::anyhow!(
                    "Generated commit message contains 'claude', which is not allowed"
                ));
            }

            github::commit_changes(&commit_message).context("Failed to commit changes")?;

            formatter.print_system("Changes committed");

            github::push_branch().context("Failed to push branch")?;

            formatter.print_system("Branch pushed to remote");

            let pr_body = format!(
                "{}\n\nFixes #{}\n\nAutomatically generated by tycode-cli --auto-pr",
                summary, issue.number
            );

            let pr_url = github::create_pr(issue.number, &issue.title, &pr_body, draft)
                .context("Failed to create pull request")?;

            formatter.print_system(&format!("Pull request created: {}", pr_url));
            println!("\nSuccessfully created PR: {}", pr_url);

            Ok(())
        }
        Err(e) => {
            formatter.print_error(&format!(
                "Auto-PR failed: {}. Branch '{}' has been left for manual inspection.",
                e, branch_name
            ));
            Err(e)
        }
    }
}

async fn request_commit_message(
    actor: &mut ChatActor,
    event_rx: &mut UnboundedReceiver<ChatEvent>,
    formatter: &mut dyn EventFormatter,
) -> Result<String> {
    let prompt = "Generate a concise conventional commit message for the changes you made. \
                  Use the format: <type>: <description>. \
                  Do not include your name or the word 'Claude' in the message. \
                  Keep it under 72 characters for the first line.";

    actor.send_message(prompt.to_string())?;

    while let Some(event) = event_rx.recv().await {
        match event {
            ChatEvent::MessageAdded(chat_message) => {
                if let MessageSender::Assistant { .. } = chat_message.sender {
                    let commit_msg = chat_message.content.trim().to_string();
                    if !commit_msg.is_empty() {
                        formatter
                            .print_system(&format!("Generated commit message: {}", commit_msg));
                        return Ok(commit_msg);
                    }
                }
            }
            ChatEvent::Error(msg) => {
                return Err(anyhow::anyhow!(
                    "Error while generating commit message: {}",
                    msg
                ));
            }
            _ => {}
        }
    }

    Err(anyhow::anyhow!(
        "Event stream ended before receiving commit message"
    ))
}
